name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run format check
      run: mix format --check-formatted
    - name: Run credo checks
      run: mix credo
    - name: Run Tests with coverage
      run: mix coveralls.html
    - name: Generate documentation
      run: mix docs
    - name: Run dialyzer checks
      run: mix dialyzer --halt-exit-status
